export type Species = "cat" | "dog" | "other";

export interface Breed {
  name: string;
  species: Species;
  popular: boolean;
  // false = adult shoulder height / build exceeds the current arch envelope
  // (9.5–15" height, 10.5–16.5" width). Captured for the future XXL version.
  fits: boolean;
  // user-typed breed not in the curated list
  custom?: boolean;
}

// Curated list. `popular` rows surface first; everything else is alphabetical.
// Sizing is judged on typical adult shoulder height & shoulder width vs. the
// arch's 9.5–15" height / 10.5–16.5" width envelope.
export const BREEDS: Breed[] = [
  // ---- Cats (essentially all fit; even Maine Coons stay within the envelope)
  { name: "Domestic Shorthair", species: "cat", popular: true, fits: true },
  { name: "Domestic Longhair", species: "cat", popular: true, fits: true },
  { name: "Maine Coon", species: "cat", popular: true, fits: true },
  { name: "Ragdoll", species: "cat", popular: true, fits: true },
  { name: "Persian", species: "cat", popular: true, fits: true },
  { name: "Siamese", species: "cat", popular: true, fits: true },
  { name: "British Shorthair", species: "cat", popular: true, fits: true },
  { name: "Bengal", species: "cat", popular: true, fits: true },
  { name: "Sphynx", species: "cat", popular: true, fits: true },
  { name: "Scottish Fold", species: "cat", popular: true, fits: true },
  { name: "Abyssinian", species: "cat", popular: false, fits: true },
  { name: "American Bobtail", species: "cat", popular: false, fits: true },
  { name: "American Curl", species: "cat", popular: false, fits: true },
  { name: "American Shorthair", species: "cat", popular: false, fits: true },
  { name: "American Wirehair", species: "cat", popular: false, fits: true },
  { name: "Balinese", species: "cat", popular: false, fits: true },
  { name: "Birman", species: "cat", popular: false, fits: true },
  { name: "Bombay", species: "cat", popular: false, fits: true },
  { name: "Burmese", species: "cat", popular: false, fits: true },
  { name: "Burmilla", species: "cat", popular: false, fits: true },
  { name: "Chartreux", species: "cat", popular: false, fits: true },
  { name: "Chausie", species: "cat", popular: false, fits: true },
  { name: "Cornish Rex", species: "cat", popular: false, fits: true },
  { name: "Devon Rex", species: "cat", popular: false, fits: true },
  { name: "Egyptian Mau", species: "cat", popular: false, fits: true },
  { name: "European Shorthair", species: "cat", popular: false, fits: true },
  { name: "Exotic Shorthair", species: "cat", popular: false, fits: true },
  { name: "Havana Brown", species: "cat", popular: false, fits: true },
  { name: "Himalayan", species: "cat", popular: false, fits: true },
  { name: "Japanese Bobtail", species: "cat", popular: false, fits: true },
  { name: "Khao Manee", species: "cat", popular: false, fits: true },
  { name: "Korat", species: "cat", popular: false, fits: true },
  { name: "LaPerm", species: "cat", popular: false, fits: true },
  { name: "Lykoi", species: "cat", popular: false, fits: true },
  { name: "Manx", species: "cat", popular: false, fits: true },
  { name: "Munchkin", species: "cat", popular: false, fits: true },
  { name: "Nebelung", species: "cat", popular: false, fits: true },
  { name: "Norwegian Forest Cat", species: "cat", popular: false, fits: true },
  { name: "Ocicat", species: "cat", popular: false, fits: true },
  { name: "Oriental Longhair", species: "cat", popular: false, fits: true },
  { name: "Oriental Shorthair", species: "cat", popular: false, fits: true },
  { name: "Peterbald", species: "cat", popular: false, fits: true },
  { name: "Pixie-bob", species: "cat", popular: false, fits: true },
  { name: "Ragamuffin", species: "cat", popular: false, fits: true },
  { name: "Russian Blue", species: "cat", popular: false, fits: true },
  { name: "Savannah", species: "cat", popular: false, fits: true },
  { name: "Selkirk Rex", species: "cat", popular: false, fits: true },
  { name: "Siberian", species: "cat", popular: false, fits: true },
  { name: "Singapura", species: "cat", popular: false, fits: true },
  { name: "Snowshoe", species: "cat", popular: false, fits: true },
  { name: "Somali", species: "cat", popular: false, fits: true },
  { name: "Tonkinese", species: "cat", popular: false, fits: true },
  { name: "Toyger", species: "cat", popular: false, fits: true },
  { name: "Turkish Angora", species: "cat", popular: false, fits: true },
  { name: "Turkish Van", species: "cat", popular: false, fits: true },

  // ---- Dogs: small breeds (fit comfortably)
  { name: "Chihuahua", species: "dog", popular: true, fits: true },
  { name: "Yorkshire Terrier", species: "dog", popular: true, fits: true },
  { name: "Pomeranian", species: "dog", popular: true, fits: true },
  { name: "French Bulldog", species: "dog", popular: true, fits: true },
  { name: "Dachshund", species: "dog", popular: true, fits: true },
  { name: "Pug", species: "dog", popular: true, fits: true },
  { name: "Shih Tzu", species: "dog", popular: true, fits: true },
  { name: "Miniature Poodle", species: "dog", popular: true, fits: true },
  { name: "Maltese", species: "dog", popular: true, fits: true },
  { name: "Cavalier King Charles Spaniel", species: "dog", popular: true, fits: true },

  // ---- Dogs: popular but too big for the current arch
  { name: "Labrador Retriever", species: "dog", popular: true, fits: false },
  { name: "Golden Retriever", species: "dog", popular: true, fits: false },
  { name: "German Shepherd", species: "dog", popular: true, fits: false },
  { name: "Bernese Mountain Dog", species: "dog", popular: true, fits: false },
  { name: "Old English Sheepdog", species: "dog", popular: true, fits: false },

  // ---- Dogs: alphabetical (mixed sizing)
  { name: "Affenpinscher", species: "dog", popular: false, fits: true },
  { name: "Afghan Hound", species: "dog", popular: false, fits: false },
  { name: "Airedale Terrier", species: "dog", popular: false, fits: false },
  { name: "Akita", species: "dog", popular: false, fits: false },
  { name: "Alaskan Klee Kai", species: "dog", popular: false, fits: true },
  { name: "Alaskan Malamute", species: "dog", popular: false, fits: false },
  { name: "American Bully", species: "dog", popular: false, fits: false },
  { name: "American Eskimo Dog", species: "dog", popular: false, fits: false },
  { name: "American Foxhound", species: "dog", popular: false, fits: false },
  { name: "American Staffordshire Terrier", species: "dog", popular: false, fits: false },
  { name: "Anatolian Shepherd", species: "dog", popular: false, fits: false },
  { name: "Australian Cattle Dog", species: "dog", popular: false, fits: false },
  { name: "Australian Kelpie", species: "dog", popular: false, fits: false },
  { name: "Australian Shepherd", species: "dog", popular: false, fits: false },
  { name: "Australian Terrier", species: "dog", popular: false, fits: true },
  { name: "Basenji", species: "dog", popular: false, fits: true },
  { name: "Basset Hound", species: "dog", popular: false, fits: false },
  { name: "Beagle", species: "dog", popular: false, fits: true },
  { name: "Bearded Collie", species: "dog", popular: false, fits: false },
  { name: "Bedlington Terrier", species: "dog", popular: false, fits: true },
  { name: "Belgian Malinois", species: "dog", popular: false, fits: false },
  { name: "Belgian Sheepdog", species: "dog", popular: false, fits: false },
  { name: "Belgian Tervuren", species: "dog", popular: false, fits: false },
  { name: "Bichon Frise", species: "dog", popular: false, fits: true },
  { name: "Black Russian Terrier", species: "dog", popular: false, fits: false },
  { name: "Bloodhound", species: "dog", popular: false, fits: false },
  { name: "Bluetick Coonhound", species: "dog", popular: false, fits: false },
  { name: "Border Collie", species: "dog", popular: false, fits: false },
  { name: "Border Terrier", species: "dog", popular: false, fits: true },
  { name: "Borzoi", species: "dog", popular: false, fits: false },
  { name: "Boston Terrier", species: "dog", popular: false, fits: true },
  { name: "Bouvier des Flandres", species: "dog", popular: false, fits: false },
  { name: "Boxer", species: "dog", popular: false, fits: false },
  { name: "Boykin Spaniel", species: "dog", popular: false, fits: false },
  { name: "Briard", species: "dog", popular: false, fits: false },
  { name: "Brittany", species: "dog", popular: false, fits: false },
  { name: "Brussels Griffon", species: "dog", popular: false, fits: true },
  { name: "Bull Terrier", species: "dog", popular: false, fits: false },
  { name: "Bullmastiff", species: "dog", popular: false, fits: false },
  { name: "Bulldog", species: "dog", popular: false, fits: false },
  { name: "Cairn Terrier", species: "dog", popular: false, fits: true },
  { name: "Cane Corso", species: "dog", popular: false, fits: false },
  { name: "Cardigan Welsh Corgi", species: "dog", popular: false, fits: true },
  { name: "Catahoula Leopard Dog", species: "dog", popular: false, fits: false },
  { name: "Caucasian Shepherd", species: "dog", popular: false, fits: false },
  { name: "Cavachon", species: "dog", popular: false, fits: true },
  { name: "Cavapoo", species: "dog", popular: false, fits: true },
  { name: "Cesky Terrier", species: "dog", popular: false, fits: true },
  { name: "Chesapeake Bay Retriever", species: "dog", popular: false, fits: false },
  { name: "Chinese Crested", species: "dog", popular: false, fits: true },
  { name: "Chinook", species: "dog", popular: false, fits: false },
  { name: "Chiweenie", species: "dog", popular: false, fits: true },
  { name: "Chow Chow", species: "dog", popular: false, fits: false },
  { name: "Clumber Spaniel", species: "dog", popular: false, fits: false },
  { name: "Cocker Spaniel", species: "dog", popular: false, fits: true },
  { name: "Cockapoo", species: "dog", popular: false, fits: true },
  { name: "Collie", species: "dog", popular: false, fits: false },
  { name: "Coton de Tulear", species: "dog", popular: false, fits: true },
  { name: "Curly-Coated Retriever", species: "dog", popular: false, fits: false },
  { name: "Dalmatian", species: "dog", popular: false, fits: false },
  { name: "Dandie Dinmont Terrier", species: "dog", popular: false, fits: true },
  { name: "Doberman Pinscher", species: "dog", popular: false, fits: false },
  { name: "Dogo Argentino", species: "dog", popular: false, fits: false },
  { name: "Dogue de Bordeaux", species: "dog", popular: false, fits: false },
  { name: "Dutch Shepherd", species: "dog", popular: false, fits: false },
  { name: "English Cocker Spaniel", species: "dog", popular: false, fits: true },
  { name: "English Foxhound", species: "dog", popular: false, fits: false },
  { name: "English Mastiff", species: "dog", popular: false, fits: false },
  { name: "English Setter", species: "dog", popular: false, fits: false },
  { name: "English Springer Spaniel", species: "dog", popular: false, fits: false },
  { name: "English Toy Spaniel", species: "dog", popular: false, fits: true },
  { name: "Eurasier", species: "dog", popular: false, fits: false },
  { name: "Field Spaniel", species: "dog", popular: false, fits: false },
  { name: "Finnish Lapphund", species: "dog", popular: false, fits: true },
  { name: "Finnish Spitz", species: "dog", popular: false, fits: false },
  { name: "Flat-Coated Retriever", species: "dog", popular: false, fits: false },
  { name: "Fox Terrier", species: "dog", popular: false, fits: true },
  { name: "German Pinscher", species: "dog", popular: false, fits: false },
  { name: "German Shorthaired Pointer", species: "dog", popular: false, fits: false },
  { name: "German Wirehaired Pointer", species: "dog", popular: false, fits: false },
  { name: "Giant Schnauzer", species: "dog", popular: false, fits: false },
  { name: "Glen of Imaal Terrier", species: "dog", popular: false, fits: true },
  { name: "Goldendoodle", species: "dog", popular: false, fits: false },
  { name: "Gordon Setter", species: "dog", popular: false, fits: false },
  { name: "Great Dane", species: "dog", popular: false, fits: false },
  { name: "Great Pyrenees", species: "dog", popular: false, fits: false },
  { name: "Greater Swiss Mountain Dog", species: "dog", popular: false, fits: false },
  { name: "Greyhound", species: "dog", popular: false, fits: false },
  { name: "Harrier", species: "dog", popular: false, fits: false },
  { name: "Havanese", species: "dog", popular: false, fits: true },
  { name: "Ibizan Hound", species: "dog", popular: false, fits: false },
  { name: "Icelandic Sheepdog", species: "dog", popular: false, fits: true },
  { name: "Irish Setter", species: "dog", popular: false, fits: false },
  { name: "Irish Terrier", species: "dog", popular: false, fits: false },
  { name: "Irish Water Spaniel", species: "dog", popular: false, fits: false },
  { name: "Irish Wolfhound", species: "dog", popular: false, fits: false },
  { name: "Italian Greyhound", species: "dog", popular: false, fits: true },
  { name: "Jack Russell Terrier", species: "dog", popular: false, fits: true },
  { name: "Japanese Chin", species: "dog", popular: false, fits: true },
  { name: "Japanese Spitz", species: "dog", popular: false, fits: true },
  { name: "Keeshond", species: "dog", popular: false, fits: false },
  { name: "Kerry Blue Terrier", species: "dog", popular: false, fits: false },
  { name: "King Charles Spaniel", species: "dog", popular: false, fits: true },
  { name: "Komondor", species: "dog", popular: false, fits: false },
  { name: "Kuvasz", species: "dog", popular: false, fits: false },
  { name: "Labradoodle", species: "dog", popular: false, fits: false },
  { name: "Lagotto Romagnolo", species: "dog", popular: false, fits: false },
  { name: "Lakeland Terrier", species: "dog", popular: false, fits: true },
  { name: "Lancashire Heeler", species: "dog", popular: false, fits: true },
  { name: "Leonberger", species: "dog", popular: false, fits: false },
  { name: "Lhasa Apso", species: "dog", popular: false, fits: true },
  { name: "Lowchen", species: "dog", popular: false, fits: true },
  { name: "Maltipoo", species: "dog", popular: false, fits: true },
  { name: "Manchester Terrier", species: "dog", popular: false, fits: true },
  { name: "Mastiff", species: "dog", popular: false, fits: false },
  { name: "Miniature American Shepherd", species: "dog", popular: false, fits: true },
  { name: "Miniature Bull Terrier", species: "dog", popular: false, fits: true },
  { name: "Miniature Pinscher", species: "dog", popular: false, fits: true },
  { name: "Miniature Schnauzer", species: "dog", popular: false, fits: true },
  { name: "Mixed Breed", species: "dog", popular: false, fits: true },
  { name: "Mudi", species: "dog", popular: false, fits: false },
  { name: "Neapolitan Mastiff", species: "dog", popular: false, fits: false },
  { name: "Newfoundland", species: "dog", popular: false, fits: false },
  { name: "Norfolk Terrier", species: "dog", popular: false, fits: true },
  { name: "Norwegian Buhund", species: "dog", popular: false, fits: false },
  { name: "Norwegian Elkhound", species: "dog", popular: false, fits: false },
  { name: "Norwich Terrier", species: "dog", popular: false, fits: true },
  { name: "Nova Scotia Duck Tolling Retriever", species: "dog", popular: false, fits: false },
  { name: "Otterhound", species: "dog", popular: false, fits: false },
  { name: "Papillon", species: "dog", popular: false, fits: true },
  { name: "Pekingese", species: "dog", popular: false, fits: true },
  { name: "Pembroke Welsh Corgi", species: "dog", popular: false, fits: true },
  { name: "Petit Basset Griffon Vendeen", species: "dog", popular: false, fits: true },
  { name: "Pharaoh Hound", species: "dog", popular: false, fits: false },
  { name: "Pit Bull", species: "dog", popular: false, fits: false },
  { name: "Plott Hound", species: "dog", popular: false, fits: false },
  { name: "Pointer", species: "dog", popular: false, fits: false },
  { name: "Polish Lowland Sheepdog", species: "dog", popular: false, fits: true },
  { name: "Pomsky", species: "dog", popular: false, fits: true },
  { name: "Portuguese Water Dog", species: "dog", popular: false, fits: false },
  { name: "Puggle", species: "dog", popular: false, fits: true },
  { name: "Puli", species: "dog", popular: false, fits: false },
  { name: "Pumi", species: "dog", popular: false, fits: true },
  { name: "Rat Terrier", species: "dog", popular: false, fits: true },
  { name: "Redbone Coonhound", species: "dog", popular: false, fits: false },
  { name: "Rhodesian Ridgeback", species: "dog", popular: false, fits: false },
  { name: "Rottweiler", species: "dog", popular: false, fits: false },
  { name: "Saint Bernard", species: "dog", popular: false, fits: false },
  { name: "Saluki", species: "dog", popular: false, fits: false },
  { name: "Samoyed", species: "dog", popular: false, fits: false },
  { name: "Schipperke", species: "dog", popular: false, fits: true },
  { name: "Schnauzer (Standard)", species: "dog", popular: false, fits: false },
  { name: "Scottish Deerhound", species: "dog", popular: false, fits: false },
  { name: "Scottish Terrier", species: "dog", popular: false, fits: true },
  { name: "Sealyham Terrier", species: "dog", popular: false, fits: true },
  { name: "Shar-Pei", species: "dog", popular: false, fits: false },
  { name: "Sheepadoodle", species: "dog", popular: false, fits: false },
  { name: "Shetland Sheepdog", species: "dog", popular: false, fits: true },
  { name: "Shiba Inu", species: "dog", popular: false, fits: false },
  { name: "Shorkie", species: "dog", popular: false, fits: true },
  { name: "Siberian Husky", species: "dog", popular: false, fits: false },
  { name: "Silky Terrier", species: "dog", popular: false, fits: true },
  { name: "Skye Terrier", species: "dog", popular: false, fits: true },
  { name: "Sloughi", species: "dog", popular: false, fits: false },
  { name: "Soft Coated Wheaten Terrier", species: "dog", popular: false, fits: false },
  { name: "Spanish Water Dog", species: "dog", popular: false, fits: false },
  { name: "Spinone Italiano", species: "dog", popular: false, fits: false },
  { name: "Staffordshire Bull Terrier", species: "dog", popular: false, fits: false },
  { name: "Standard Poodle", species: "dog", popular: false, fits: false },
  { name: "Sussex Spaniel", species: "dog", popular: false, fits: true },
  { name: "Swedish Vallhund", species: "dog", popular: false, fits: true },
  { name: "Tibetan Mastiff", species: "dog", popular: false, fits: false },
  { name: "Tibetan Spaniel", species: "dog", popular: false, fits: true },
  { name: "Tibetan Terrier", species: "dog", popular: false, fits: true },
  { name: "Toy Poodle", species: "dog", popular: false, fits: true },
  { name: "Treeing Walker Coonhound", species: "dog", popular: false, fits: false },
  { name: "Vizsla", species: "dog", popular: false, fits: false },
  { name: "Weimaraner", species: "dog", popular: false, fits: false },
  { name: "Welsh Springer Spaniel", species: "dog", popular: false, fits: false },
  { name: "Welsh Terrier", species: "dog", popular: false, fits: true },
  { name: "West Highland White Terrier", species: "dog", popular: false, fits: true },
  { name: "Whippet", species: "dog", popular: false, fits: false },
  { name: "Wire Fox Terrier", species: "dog", popular: false, fits: true },
  { name: "Wirehaired Pointing Griffon", species: "dog", popular: false, fits: false },
  { name: "Xoloitzcuintli", species: "dog", popular: false, fits: false },
  { name: "Yorkipoo", species: "dog", popular: false, fits: true },
];
